platform :ios, :deployment_target => '8.0'
inhibit_all_warnings!

link_with 'MiniMonsterIOS'

target 'MiniMonsterIOS' do

pod 'AFNetworking', '~>2.5'
pod 'SVProgressHUD'
pod 'UIImage-Categories'
pod 'XLYKeyValueStore'
pod 'MagicalRecord'
pod 'UIAlertView+Blocks'
pod 'Fabric'
pod 'Crashlytics'
pod 'UITextView+Placeholder'
end